[application]
name = "smarts-evolution-web"
default_platform = "web"
out_dir = "dist"

[web.app]
title = ""
base_path = "/"

[web.watcher]
reload_html = true
watch_path = ["index.html", "src", "assets", "public"]
